### ISSUE TITLE
Dosen't work in linux.

### ISSUE THREAD

**Issue by banjofan2780** [RareExports/io_scene_obj_rgba#1]
Hello! I tried to install this addon in linux but i get this error when installing the addon and clicking the checkbox. Modules Installed () from '/home/winesap/Downloads/io_scene_obj_rgba-main.zip' into '/home/winesap/.config/blender/3.2/scripts/addons'
bpy.context.space_data.recent_folders_active = 1
bpy.context.space_data.recent_folders_active = 1
Traceback (most recent call last):
  File "/home/winesap/Downloads/blender-3.2.0-linux-x64/3.2/scripts/modules/addon_utils.py", line 335, in enable
    mod = __import__(module_name)
  File "/home/winesap/.config/blender/3.2/scripts/addons/io_scene_obj_rgba-main/__init__.py", line 48, in <module>
    from bpy_extras.io_utils import (
ImportError: cannot import name 'orientation_helper_factory' from 'bpy_extras.io_utils' (/home/winesap/Downloads/blender-3.2.0-linux-x64/3.2/scripts/modules/bpy_extras/io_utils.py)

**Comment by Zeldaboy14** [comment]
This plugin is written for legacy blender, not modern blender. Check my github for a 3.1+ version of the script
